name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
          
      - name: Create dist directory
        run: mkdir -p dist

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/aiyou-cli.exe
        
      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/aiyou-cli

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl
          
      - name: Compress binaries with UPX
        run: |
          upx --best --lzma dist/aiyou-cli.exe
          upx --best --lzma dist/aiyou-cli
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/aiyou-cli.exe
            dist/aiyou-cli
          draft: false
          prerelease: false
          generate_release_notes: true
